### PR TITLE
examples/aio_pika_server.py: Add missing RPC method sum(a, b)

### PR DESCRIPTION
**Pull request by bernhardkaindl**
Add RPC method implementing `examples/aio_pika_client.py`'s calls to `sum(1, 2)`

### CODE REVIEW

**Comment by bernhardkaindl** [comment]
@dapper91 maybe you'd like to merge this and #59, just sending this comment so you see it hopefully (and approve or add me a developer)

**Comment by bernhardkaindl** [comment]
@dapper91 ping, are you still there? Thanks for this cool project!

**Comment by dapper91** [comment]
Please, change target branch from master to dev.

**Comment by bernhardkaindl** [comment]
@dapper91 done!

**Pull request merged**
